#server:
#  port: 8761
#
#security:
#    user:
#        name: duke
#        password: duke
#    basic:
#        enabled: true
#
#management:
#    context-path: /management
#    security:
#        enabled: false

server:
  port: 8761

#服务发现服务端配置
eureka:
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka
    register-with-eureka: false #是否将自己注册到eureka服务器
    fetch-registry: false #是否从eureka服务器获取服务注册列表

#为eurekaserver添加认证
security:
  user:
    name: duke
    password: duke
  basic:
    enabled: true
